### ISSUE TITLE
Use the official Postgres image

### ISSUE THREAD

**Issue by zedtux** [abevoelker/docker-postgres#11]
This would avoid you to maintain the postgres part. The Postgres Docker image has evolved a lot in a year, and today the current stable is 9.5.

This Docker image looks awesome, but I don't want to downgrade my DB.

**Comment by zedtux** [comment]
This repo description is about Postgres 9.3, but the first line from the `README.md` file is about Postgres 9.5. In my opinion, the Postgres version shouldn't be specified.

A tag of this repo docker image should match with each tags from the offical postgres image like the following:

| Official Postgres image | Docker Wall-e |
| --- | --- |
| 9.3.11 | 9.3.11 |
| 9.4.6 | 9.4.6 |
| 9.5.1 | 9.5.1 |

**Comment by abevoelker** [comment]
Great idea! I've kinda let this image decay since I don't use it much anymore. Would like to replace supervisord with a better init too.

**Comment by zedtux** [comment]
> I've kinda let this image decay since I don't use it much anymore.

I guess it's still the case so I'm closing this issue.
